### ISSUE TITLE
No support for TTC files and doesn't find fonts beginning with @-sign

### ISSUE THREAD

**Issue by Sheigutn** [Myaamori/SubKt#21]
Seems like SubKt doesn't support TTC files (TrueType collection) that have multiple fonts in one file.
It also doesn't find fonts starting with an @-sign (https://devblogs.microsoft.com/oldnewthing/20120719-00/?p=7093), though I was able to fix that with a short snippet of code: https://github.com/Sheigutn/SubKt/commit/526e24d22a47be684e235ff4dcfaeb5c98b81741
I'm not sure if you want to fix it exactly like that though, so I'm not submitting it as a pull request (yet).
Also, I really wanna thank you for this tool, it's very useful! :)

**Comment by Myaamori** [comment]
Hmm that's strange, it should be stripping leading `@` [here](https://github.com/Myaamori/SubKt/blob/master/src/main/kotlin/myaa/subkt/tasks/utils/fontvalidator.kt#L37), and I just did a quick test to confirm that it seems to work on my end. Would you be able to provide an example where it breaks?

I just pushed a quick attempt at supporting TTC fonts; if you want to test it now, you can try cloning the repository and running Gradle with the `--include-build path/to/subkt` option, otherwise I'll be putting out a new version that includes the fix at some point.

**Comment by Sheigutn** [comment]
TTC fonts work perfectly now, thank you. And I see where the problem is, I have styles with a font with a leading @, but you're not stripping those [here](https://github.com/Myaamori/SubKt/blob/953052ead268e83b1310332eb08fae17ff45da3a/src/main/kotlin/myaa/subkt/tasks/utils/fontvalidator.kt#L372). After I stripped it there too, the plugin worked flawlessly.

**Comment by Myaamori** [comment]
Ah, it never even crossed my mind that you could use `@` in style definitions too. I'll fix it, thank you for the report!
